In [1]:
#dependencies
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as f
from torch.utils.data import DataLoader,TensorDataset
from torch.optim import Adam

In [2]:
path='D:/Data Science/Machine Learning/Machine_Learning/Machine-Learning-A-Z-New/Machine Learning A-Z New\Part 2 - Regression/Section 5 - Multiple Linear Regression/'
df=pd.read_csv(path+'50_Startups.csv')

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,3]=le.fit_transform(x[:,3])

In [6]:
x[:4]

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2]], dtype=object)

In [7]:
x.shape

(50, 4)

In [8]:
y=y.astype(dtype='float64')
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [9]:
x=x.astype(dtype='float64') #we had to convert the array to float because one col was int because it was encoded
x[:2]       #so we casted entire array as float array because tensors doesn't entertains heterogenous data types

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00]])

In [10]:
#two ways to convert arrays to tensors
x=torch.tensor(x) #first 
y=torch.from_numpy(y) #second
print(x[:2])
print(y[:2])

tensor([[1.6535e+05, 1.3690e+05, 4.7178e+05, 2.0000e+00],
        [1.6260e+05, 1.5138e+05, 4.4390e+05, 0.0000e+00]], dtype=torch.float64)
tensor([192261.8300, 191792.0600], dtype=torch.float64)


In [11]:
#definiing model
model=nn.Linear(x.shape[1],1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3879, -0.1967, -0.2104,  0.2840]], requires_grad=True)
Parameter containing:
tensor([0.3466], requires_grad=True)


In [12]:
#to view all the model parameters
print(model.parameters)
print(list(model.parameters()))

<bound method Module.parameters of Linear(in_features=4, out_features=1, bias=True)>
[Parameter containing:
tensor([[-0.3879, -0.1967, -0.2104,  0.2840]], requires_grad=True), Parameter containing:
tensor([0.3466], requires_grad=True)]


In [13]:
y_pred=model(x.float())
print(y_pred)

tensor([[-190310.0156],
        [-186225.6406],
        [-165226.7500],
        [-159953.2656],
        [-150125.6875],
        [-147118.6719],
        [-108036.2109],
        [-147298.6406],
        [-141562.0312],
        [-133373.9531],
        [-109491.5078],
        [-109641.4922],
        [-114009.9375],
        [-115486.8984],
        [-131278.5938],
        [-123608.6484],
        [-109788.2656],
        [-124696.8984],
        [-120087.3203],
        [ -63717.2852],
        [-114804.6797],
        [-123708.4453],
        [-116661.1562],
        [-111109.2266],
        [ -78984.4219],
        [ -81556.2734],
        [ -85770.6797],
        [-127418.5234],
        [ -86402.7188],
        [ -78087.7578],
        [ -65964.6016],
        [ -72309.2500],
        [ -59708.4141],
        [ -86948.8672],
        [ -93372.9141],
        [ -77810.7812],
        [ -78421.8281],
        [ -68629.5781],
        [ -59792.2656],
        [ -68093.3047],
        [ -70823.1953],
        [ -62081

In [14]:
#loss function
mse=f.mse_loss
loss=mse(y_pred.squeeze(1),y)
print(loss.double())

tensor(4.9871e+10, dtype=torch.float64, grad_fn=<MseLossBackward>)


In [15]:
opt=Adam(model.parameters(),lr=1e-2)

In [16]:
trainset=TensorDataset(x,y)
trainset[:2]

(tensor([[1.6535e+05, 1.3690e+05, 4.7178e+05, 2.0000e+00],
         [1.6260e+05, 1.5138e+05, 4.4390e+05, 0.0000e+00]], dtype=torch.float64),
 tensor([192261.8300, 191792.0600], dtype=torch.float64))

In [17]:
training_data=DataLoader(trainset,batch_size=5,shuffle=True)

In [18]:
for a,b in training_data:
    print(a)
    print(b)
    break

tensor([[6.4665e+04, 1.3955e+05, 1.3796e+05, 0.0000e+00],
        [0.0000e+00, 1.3543e+05, 0.0000e+00, 0.0000e+00],
        [6.1994e+04, 1.1564e+05, 9.1131e+04, 1.0000e+00],
        [2.2178e+04, 1.5481e+05, 2.8335e+04, 0.0000e+00],
        [2.7893e+04, 8.4711e+04, 1.6447e+05, 1.0000e+00]], dtype=torch.float64)
tensor([107404.3400,  42559.7300,  99937.5900,  65200.3300,  77798.8300],
       dtype=torch.float64)


In [ ]:
epochs=100000
for epoch in range(epochs):
    for inputs,targets in training_data:
        pred=model(inputs.float())
        pred=pred.squeeze(1)
        #print(pred.shape)
        #print(inputs.dtype)
        #print(targets.dtype)
        #print(y_pred.dtype)
        pred=pred.double()
        loss=mse(pred,targets)
        loss.backward() #computing gradients
        opt.step() #updating parameters
        opt.zero_grad() #setting the grads back to zero
    if epoch%1000==0:
        #print(f'Epoch:{epoch}/{epochs} | Loss:{loss.item()}')
        pass